DROP TABLE IF EXISTS `accounting_log`;
CREATE TABLE IF NOT EXISTS `accounting_log` (
  `accl_id` bigint NOT NULL AUTO_INCREMENT,
  `branch_no` int UNSIGNED NOT NULL DEFAULT '0',
  `station_no` int UNSIGNED DEFAULT '0',
  `moncl_no` int UNSIGNED DEFAULT NULL,
  `accl_type` tinyint UNSIGNED DEFAULT NULL,
  `accl_type_no` int UNSIGNED DEFAULT NULL,
  `accl_date` date DEFAULT NULL,
  `accl_time` time DEFAULT NULL,
  `opera_no` int UNSIGNED DEFAULT NULL,
  `accl_changed_date` datetime DEFAULT NULL,
  `accl_first_slip_no` bigint UNSIGNED DEFAULT '0',
  `accl_last_slip_no` bigint UNSIGNED DEFAULT '0',
  `accl_accounting_date` date DEFAULT NULL,
  `accl_pdf` longblob,
  `accl_atm_accounting` longtext,
  PRIMARY KEY (`accl_id`),
  KEY `accounting_log_branch_no_ckey` (`branch_no`),
  KEY `accounting_log_station_no_ckey` (`station_no`),
  KEY `accounting_log_moncl_no_ckey` (`moncl_no`),
  KEY `accounting_log_accl_type_ckey` (`accl_type`),
  KEY `accounting_log_accl_type_no_ckey` (`accl_type_no`),
  KEY `accounting_log_accl_date_ckey` (`accl_date`),
  KEY `accounting_log_accl_time_ckey` (`accl_time`),
  KEY `accounting_log_opera_no_ckey` (`opera_no`),
  KEY `accounting_log_accl_changed_date_ckey` (`accl_changed_date`),
  KEY `accounting_log_accl_last_slip_no_ckey` (`accl_last_slip_no`),
  KEY `accounting_log_accl_key_type_ckey` (`station_no`,`accl_type`,`accl_type_no`),
  KEY `accounting_log_accl_key_money_counting_ckey` (`station_no`,`moncl_no`),
  KEY `accounting_log_accl_key_log_ckey` (`station_no`,`accl_type`,`opera_no`,`accl_last_slip_no`),
  KEY `accounting_log_accl_key_branch_ckey` (`branch_no`,`station_no`,`accl_type`,`accl_type_no`)
);

