name: tests

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          tools: composer:v2
          coverage: xdebug

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install Node Dependencies
        run: npm ci

      - name: Build Assets
        run: npm run build

      - name: Install Dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Copy Environment File
        run: cp .env.example .env

      - name: Setup Environment
        run: |
          echo "DB_CONNECTION=sqlite" >> .env  
          echo "DB_DATABASE=:memory:" >> .env
          echo "SESSION_DRIVER=array" >> .env
          echo "CACHE_STORE=array" >> .env
          echo "QUEUE_CONNECTION=sync" >> .env
          # Remove any MySQL configuration that might interfere
          sed -i '/^DB_HOST=/d' .env || true
          sed -i '/^DB_PORT=/d' .env || true
          sed -i '/^DB_USERNAME=/d' .env || true
          sed -i '/^DB_PASSWORD=/d' .env || true  

      - name: Generate Application Key
        run: php artisan key:generate

      - name: Generate Passport Keys
        run: php artisan passport:keys

      - name: Run Database Migrations
        run: php artisan migrate --force

      - name: Tests
        run: ./vendor/bin/pest
